"""Added post table

Revision ID: 331eecfca27a
Revises: 2c2af4a069b5
Create Date: 2023-01-11 17:08:49.158897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331eecfca27a'
down_revision = '2c2af4a069b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('msg', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
